# Generated by Django 5.0.1 on 2026-01-19 23:46

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم الفصل"
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=20, verbose_name="العام الدراسي"),
                ),
                (
                    "semester_number",
                    models.PositiveIntegerField(verbose_name="رقم الفصل"),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="الفصل الحالي"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "فصل دراسي",
                "verbose_name_plural": "الفصول الدراسية",
                "ordering": ["-academic_year", "-semester_number"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="اسم المقرر")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="رمز المقرر"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="وصف المقرر"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="accounts.level",
                        verbose_name="المستوى",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقرر",
                "verbose_name_plural": "المقررات",
            },
        ),
        migrations.CreateModel(
            name="CourseMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.major"
                    ),
                ),
            ],
            options={
                "verbose_name": "تخصص المقرر",
                "verbose_name_plural": "تخصصات المقررات",
                "unique_together": {("course", "major")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="majors",
            field=models.ManyToManyField(
                related_name="courses",
                through="core.CourseMajor",
                to="accounts.major",
                verbose_name="التخصصات",
            ),
        ),
        migrations.CreateModel(
            name="InstructorCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(auto_now_add=True, verbose_name="تاريخ التعيين"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تعيين مدرس",
                "verbose_name_plural": "تعيينات المدرسين",
                "unique_together": {("instructor", "course")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                related_name="teaching_courses",
                through="core.InstructorCourse",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المدرسين",
            ),
        ),
        migrations.CreateModel(
            name="LectureFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="الوصف"),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("local_file", "ملف محلي"),
                            ("external_link", "رابط خارجي"),
                        ],
                        default="local_file",
                        max_length=20,
                        verbose_name="نوع المحتوى",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.lecture_file_path,
                        verbose_name="الملف",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="الرابط الخارجي"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("lecture", "محاضرة"),
                            ("summary", "ملخص"),
                            ("exam", "اختبار"),
                            ("assignment", "واجب"),
                            ("reference", "مرجع"),
                            ("other", "أخرى"),
                        ],
                        default="lecture",
                        max_length=50,
                        verbose_name="نوع الملف",
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="حجم الملف"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="مرئي")),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="محذوف"),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد التحميلات"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات"
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الرفع"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الرافع",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف محاضرة",
                "verbose_name_plural": "ملفات المحاضرات",
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("file_upload", "رفع ملف جديد"),
                            ("announcement", "إعلان"),
                            ("system", "نظام"),
                        ],
                        default="announcement",
                        max_length=50,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "target_all_students",
                    models.BooleanField(default=False, verbose_name="لجميع الطلاب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.course",
                        verbose_name="المقرر",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="core.semester",
                verbose_name="الفصل الدراسي",
            ),
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="core.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مستلم إشعار",
                "verbose_name_plural": "مستلمي الإشعارات",
                "unique_together": {("notification", "user")},
            },
        ),
    ]
