# Generated by Django 5.0.1 on 2026-01-19 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="السؤال")),
                ("answer", models.TextField(verbose_name="الإجابة")),
                (
                    "is_helpful",
                    models.BooleanField(blank=True, null=True, verbose_name="مفيد"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to="core.lecturefile",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "محادثة AI",
                "verbose_name_plural": "محادثات AI",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "سهل"), ("medium", "متوسط"), ("hard", "صعب")],
                        default="medium",
                        max_length=20,
                        verbose_name="مستوى الصعوبة",
                    ),
                ),
                ("questions_json", models.JSONField(verbose_name="الأسئلة")),
                (
                    "questions_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الأسئلة"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0, verbose_name="وقت المعالجة (ثانية)"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التوليد"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_questions",
                        to="core.lecturefile",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_questions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "أسئلة AI",
                "verbose_name_plural": "أسئلة AI",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(max_length=50, verbose_name="نوع الطلب"),
                ),
                (
                    "request_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الطلب"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_rate_limits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "حد استخدام AI",
                "verbose_name_plural": "حدود استخدام AI",
                "ordering": ["-request_time"],
            },
        ),
        migrations.CreateModel(
            name="AISummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("brief", "ملخص موجز"),
                            ("detailed", "ملخص تفصيلي"),
                            ("key_points", "نقاط رئيسية"),
                        ],
                        default="brief",
                        max_length=20,
                        verbose_name="نوع الملخص",
                    ),
                ),
                ("summary_text", models.TextField(verbose_name="نص الملخص")),
                (
                    "word_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الكلمات"),
                ),
                (
                    "processing_time",
                    models.FloatField(default=0, verbose_name="وقت المعالجة (ثانية)"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ التوليد"
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summaries",
                        to="core.lecturefile",
                        verbose_name="الملف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_summaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملخص AI",
                "verbose_name_plural": "ملخصات AI",
                "ordering": ["-generated_at"],
            },
        ),
    ]
