# Generated by Django 5.0.1 on 2026-01-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="المتصفح"),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "تسجيل دخول"),
                    ("logout", "تسجيل خروج"),
                    ("file_upload", "رفع ملف"),
                    ("file_download", "تحميل ملف"),
                    ("file_view", "عرض ملف"),
                    ("ai_summary", "توليد ملخص AI"),
                    ("ai_questions", "توليد أسئلة AI"),
                    ("ai_chat", "محادثة AI"),
                    ("notification_sent", "إرسال إشعار"),
                    ("account_activated", "تفعيل حساب"),
                    ("password_reset", "إعادة تعيين كلمة المرور"),
                ],
                max_length=50,
                verbose_name="الإجراء",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "action"], name="accounts_us_user_id_ea3818_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_4de55c_idx"
            ),
        ),
    ]
