# Generated by Django 5.0.1 on 2026-01-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_useractivity_user_agent_alter_useractivity_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="covers/", verbose_name="صورة الغلاف"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                choices=[("ar", "العربية"), ("en", "English")],
                default="ar",
                max_length=5,
                verbose_name="اللغة المفضلة",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_theme",
            field=models.CharField(
                choices=[("dark", "الوضع الليلي"), ("light", "الوضع الفاتح")],
                default="dark",
                max_length=10,
                verbose_name="المظهر المفضل",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profiles/",
                verbose_name="صورة الملف الشخصي",
            ),
        ),
    ]
